# fly.toml app configuration file for olyticket

app = "olyticket"
primary_region = "fra"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[mounts]
source = "data"
destination = "/app/data"
